version: "2.4"
services:
  db:
    image: postgres:12-alpine 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
  api:
    build: .
    depends_on:
       db:
        condition: service_healthy
    environment:
      - DB_NAME=bank
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=password
      - APP_PORT=8080
      - SECRETKEY=topscrect
    ports:
      - "8080:8080"
volumes:
  db:
    driver: local
